Repository B12-project/trello_application, pull requests merged in 2024-07, with the labels that each got.

#9 FEAT: #7 보드 등록 기능 추가
  src/main/java/b12/trello/domain/board/controller/BoardController.java
  src/main/java/b12/trello/domain/board/dto/BoardInviteRequestDto.java
  src/main/java/b12/trello/domain/board/dto/BoardRequestDto.java
  src/main/java/b12/trello/domain/board/dto/BoardResponseDto.java
  src/main/java/b12/trello/domain/board/entity/Board.java
  src/main/java/b12/trello/domain/board/repository/BoardRepository.java
  src/main/java/b12/trello/domain/board/service/BoardService.java
  src/main/java/b12/trello/domain/boardUser/entity/BoardUser.java
  src/main/java/b12/trello/domain/boardUser/repository/BoardUserRepository.java
  src/main/java/b12/trello/global/exception/customException/BoardException.java
  src/main/java/b12/trello/global/exception/customException/BoardUserException.java
  src/main/java/b12/trello/global/exception/errorCode/BoardErrorCode.java
  src/main/java/b12/trello/global/exception/errorCode/BoardUserErrorCode.java
  src/main/resources/application.yml
  src/test/apiTest/Board.http
Labels: enhancement

#11 Fix/7 Default refactoring and builder fixes 수정, 추가
  src/main/java/b12/trello/domain/board/service/BoardService.java
  src/main/java/b12/trello/domain/boardUser/repository/BoardUserRepository.java
  src/main/java/b12/trello/global/exception/errorCode/BoardUserErrorCode.java
Labels: enhancement

#12 Feature/4 column
  src/main/java/b12/trello/domain/board/entity/Board.java
  src/main/java/b12/trello/domain/boardUser/repository/BoardUserRepository.java
  src/main/java/b12/trello/domain/column/controller/ColumnController.java
  src/main/java/b12/trello/domain/column/dto/ColumnCreateRequestDto.java
  src/main/java/b12/trello/domain/column/dto/ColumnFindRequestDto.java
  src/main/java/b12/trello/domain/column/dto/ColumnFindResponseDto.java
  src/main/java/b12/trello/domain/column/dto/ColumnModifyRequestDto.java
  src/main/java/b12/trello/domain/column/dto/ColumnOrderModifyRequestDto.java
  src/main/java/b12/trello/domain/column/dto/ColumnRequestDto.java
  src/main/java/b12/trello/domain/column/dto/ColumnResponseDto.java
  src/main/java/b12/trello/domain/column/entity/Columns.java
  src/main/java/b12/trello/domain/column/repository/ColumnRepository.java
  src/main/java/b12/trello/domain/column/service/ColumnService.java
  src/main/java/b12/trello/global/entity/TimeStamped.java
  src/main/java/b12/trello/global/exception/customException/column/BoardNotFoundException.java
  src/main/java/b12/trello/global/exception/customException/column/ColumnDuplicatedException.java
  src/main/java/b12/trello/global/exception/customException/column/ColumnNotFoundException.java
  src/main/java/b12/trello/global/exception/customException/column/InvalidOrderException.java
  src/main/java/b12/trello/global/exception/customException/column/InvalidUserException.java
  src/main/java/b12/trello/global/exception/errorCode/column/ColumnErrorCode.java
  src/test/apiTest/User.http
Labels: enhancement

#19 Feature/14 soft delete test
  src/main/java/b12/trello/domain/board/controller/BoardController.java
  src/main/java/b12/trello/domain/board/entity/Board.java
  src/main/java/b12/trello/domain/board/service/BoardService.java
  src/main/java/b12/trello/domain/boardUser/repository/BoardUserRepository.java
  src/main/java/b12/trello/domain/card/dto/request/CardListByColumnRequestDto.java
  src/main/java/b12/trello/domain/card/service/CardService.java
  src/main/java/b12/trello/domain/column/service/ColumnService.java
  src/main/java/b12/trello/domain/comment/controller/CommentController.java
  src/main/java/b12/trello/domain/comment/dto/CommentModifyRequestDto.java
  src/main/java/b12/trello/domain/comment/repository/CommentRepository.java
  src/main/java/b12/trello/domain/comment/service/CommentService.java
  src/main/java/b12/trello/domain/user/entity/User.java
  src/main/java/b12/trello/domain/user/repository/UserRepository.java
  src/main/java/b12/trello/domain/user/service/AuthService.java
  src/main/java/b12/trello/domain/user/service/UserService.java
  src/main/java/b12/trello/global/entity/TimeStampedWithDeletedAt.java
  src/main/java/b12/trello/global/exception/errorCode/BoardErrorCode.java
  src/main/java/b12/trello/global/exception/errorCode/BoardUserErrorCode.java
  src/main/java/b12/trello/global/security/UserDetailsServiceImpl.java
  src/main/java/b12/trello/global/security/filter/JwtAuthorizationFilter.java
  src/test/apiTest/Board.http
  src/test/apiTest/Card.http
  src/test/apiTest/Columns.http
  src/test/apiTest/Comment.http
  src/test/apiTest/User.http
Labels: enhancement

#23 Bugfix/22 @RequestParam 수정
  src/main/java/b12/trello/domain/card/controller/CardController.java
  src/main/java/b12/trello/domain/card/service/CardService.java
  src/main/java/b12/trello/domain/column/controller/ColumnController.java
  src/main/java/b12/trello/domain/column/service/ColumnService.java
Labels: bug

#26 Bugfix/25 BoardService 수정
  src/main/java/b12/trello/domain/board/service/BoardService.java
Labels: bug

#28 Feature/5 front web
  src/main/java/b12/trello/domain/board/controller/BoardController.java
  src/main/java/b12/trello/domain/board/dto/BoardInviteRequestDto.java
  src/main/java/b12/trello/domain/board/dto/BoardUserResponseDto.java
  src/main/java/b12/trello/domain/board/service/BoardService.java
  src/main/java/b12/trello/domain/boardUser/repository/BoardUserRepository.java
  src/main/java/b12/trello/domain/boardUser/service/BoardUserService.java
  src/main/java/b12/trello/domain/column/controller/ColumnController.java
  src/main/java/b12/trello/domain/column/dto/ColumnFindRequestDto.java
  src/main/java/b12/trello/domain/column/dto/ColumnResponseDto.java
  src/main/java/b12/trello/domain/column/entity/Columns.java
  src/main/java/b12/trello/domain/column/service/ColumnService.java
  src/main/java/b12/trello/domain/comment/entity/Comment.java
  src/main/java/b12/trello/domain/comment/service/CommentService.java
  src/main/java/b12/trello/domain/user/controller/HomeController.java
  src/main/java/b12/trello/domain/user/controller/UserController.java
  src/main/java/b12/trello/domain/user/dto/PasswordRequestDto.java
  src/main/java/b12/trello/domain/user/service/UserService.java
  src/main/java/b12/trello/global/config/AppConfig.java
  src/main/java/b12/trello/global/config/RestTemplateConfig.java
  src/main/java/b12/trello/global/config/SecurityConfig.java
  src/main/java/b12/trello/global/security/filter/JwtAuthorizationFilter.java
  src/main/resources/application.yml
  src/main/resources/static/css/style.css
  src/main/resources/static/favicon.ico
  src/main/resources/static/js/basic.js
  src/main/resources/static/js/board.js
  src/main/resources/static/js/test.js
  src/main/resources/templates/backup1.html
  src/main/resources/templates/board.html
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
  src/main/resources/templates/signup.html
  src/main/resources/templates/test.html
  src/test/apiTest/Board.http
  src/test/apiTest/Simulate2.http
  src/test/apiTest/SimulateAll.http
Labels: enhancement

#29 Feature/#5 front web
  src/main/java/b12/trello/domain/card/dto/request/CardCreateRequestDto.java
  src/main/java/b12/trello/global/security/filter/JwtAuthorizationFilter.java
  src/main/resources/static/css/style.css
  src/main/resources/static/js/basic.js
  src/main/resources/static/js/board.js
  src/main/resources/static/js/test.js
  src/main/resources/templates/backup1.html
  src/main/resources/templates/board.html
  src/main/resources/templates/index.html
  src/main/resources/templates/test.html
  src/test/java/b12/trello/TrelloApplicationTests.java
  src/test/java/testCode/test.java
Labels: bug, enhancement

#32 🎉 FEAT: #7 프론트 디자인 수정
  src/main/java/b12/trello/domain/user/controller/AuthController.java
  src/main/java/b12/trello/domain/user/service/AuthService.java
  src/main/java/b12/trello/global/security/filter/JwtAuthenticationFilter.java
  src/main/java/b12/trello/global/security/filter/JwtAuthorizationFilter.java
  src/main/java/b12/trello/global/security/util/JwtUtil.java
  src/main/resources/templates/board.html
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
Labels: enhancement
